apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  template:
    metadata:
      name: auth
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ruanxingke/auth
          ports:
            - containerPort: 8888
          env:
            - name: "PORT"
              value: "8888"
  selector:
    matchLabels:
      app: auth
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - port: 8888
      targetPort: 8888
  type: ClusterIP # internal
